### ISSUE TITLE
Checking valid JIRA ID with REST instead of OAuth

### ISSUE THREAD

**Issue by ttoleung** [mohamicorp/yet-another-commit-checker#103]
Checking through OAuth has caused some pain for us when the token expired, also we are having a new issue that generic accounts in Bamboo but not present in JIRA - no way we can check for this.

I am wondering if we can have a simpler solution is that it always check with a specific userid , through JIRA REST whether the ID existed or not, this way we don't need to set up OAuth altogether.

**Comment by george-vulov** [comment]
For the bamboo use case, try out the ["Exclude Service User Commits"](https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/1442119700/Yet+Another+Commit+Checker+YACC+for+Bitbucket#Exclude-Service-User-Commits) option.
