### ISSUE TITLE
Feature request: Merge checks on pull requests from forks

### ISSUE THREAD

**Issue by ogrim** [mohamicorp/yet-another-commit-checker#104]
Using a distributed fork-based workflow, we would like to enforce commit guidelines on pull requests. 

We have set a requirement to have a Jira issue in the commit messages, so we are not able to push the commit saying "bad msg" to our upstream repository. However, it can be merged in a pull request - bypassing the message requirements we have set.

Can this feature be implemented using the [merge-checks](https://developer.atlassian.com/stash/docs/latest/how-tos/repository-hooks.html#Merge-checks) feature?

**Comment by sford** [comment]
Hi @ogrim ,

From spot checking the merge check API, yes, I believe this is possible.

**Comment by sford** [comment]
Related: #95

**Comment by gsylvie** [comment]
[Control Freak for Bitbucket Server](https://marketplace.atlassian.com/apps/1217635/control-freak-for-bitbucket-server?hosting=server&tab=overview) implements JIRA based commit checking on merge.

**Comment by krysalead** [comment]
Hi,

I have the same requirement, my developers are using forks and can do pull-request to the main stream with commit that doesn't match the JIRA record presence constraint, thus the plugin become useless as it didn't prevent to push commit without JIRA record.

**Comment by george-vulov** [comment]
@krysalead We plan to implement turning on Yacc as a merge check rather than as push check. Should be in the next release.

**Comment by mzhumakhanov** [comment]
@george-vulov ,

> @krysalead We plan to implement turning on Yacc as a merge check rather than as push check. Should be in the next release.

It's great! Could you please share with us your plans about release, when is it planned?

**Comment by george-vulov** [comment]
> It's great! Could you please share with us your plans about release, when is it planned?

The release that has Yacc as a merge check should be out in 1-2 weeks. We may put out a small bugfix release prior to that to address the regression noted in #251

**Comment by george-vulov** [comment]
As of [version 2.0.0](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions), YACC can be enabled either as a pre-receive hook or as a merge check.
