### ISSUE TITLE
JQL checker is not working as expected

### ISSUE THREAD

**Issue by pantzjantz** [mohamicorp/yet-another-commit-checker#108]
**Environment:**
Stash 3.10.4 (two node cluster) with Netscaler load balancer. I've tried it linked to two separate Jira instances, both were v6.3.12. Stash nodes are running on CentOS 6.5.

**Testing:**
YACC 1.6 works with single node Stash 3.10.4 instance
YACC 1.6 does not work with Stash 3.10.4 cluster (I realize this is not technically compatible)
YACC 1.8 does not work with Stash 3.10.4 cluster (this is supposed to be compatible but I cannot get it to work) 

**Description:**
I've been scratching my head trying to figure out why I'm getting an error with just the JQL checker. Jira Application links work fine and 'Require valid Jira issue' checker works fine. I'm not sure why when it tries to connect to Jira to do a JQL validation it fails.

Error shown in hook configuration UI:
'Unable to validate JQL query with JIRA because there was an unexpected exception. Please see Stash logs.'

atlassian-stash.log:
2016-04-12 07:33:29,034 ERROR [http-nio-7990-exec-2] USERNAME *1HPJCYLx453x13041x0 bpxw01 10.208.100.21,127.0.0.1 "PUT /rest/api/latest/projects/ST/repos/yet-another-commit-checker/settings/hooks/com.isroot.stash.plugin.yacc:yaccHook/settings HTTP/1.1" c.i.stash.plugin.ConfigValidator unexpected exception while trying to validate jql query
com.atlassian.sal.api.net.ResponseException: java.net.SocketTimeoutException: Read timed out

**JVM:**
stash    22879     1  2 Mar22 ?        11:44:52 /opt/java/default/bin/java -Djava.util.logging.config.file=/opt/atlassian/stash/stash-current/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xms2000m -Xmx2000m -javaagent:/opt/AppDynamics/Test/current/AppServerAgent/javaagent.jar -Datlassian.org.osgi.framework.bootdelegation=META-INF.services,com.yourkit,com.singularity._,com.jprofiler,com.jprofiler._,org.apache.xerces,org.apache.xerces._,org.apache.xalan,org.apache.xalan._,sun._,com.sun.jndi,com.icl.saxon,com.icl.saxon._,javax.servlet,javax.servlet._,com.sun.xml.bind._ -Dcluster.node.name=#hostname# -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Datlassian.standalone=STASH -Dorg.apache.jasper.runtime.BodyContentImpl.LIMIT_BUFFER=true -Dmail.mime.decodeparameters=true -Dorg.apache.catalina.connector.Response.ENFORCE_ENCODING_IN_GET_WRITER=false -Djava.library.path=/opt/atlassian/stash/stash-current/lib/native:/stash-home/atlassian/application-data/stash/lib/native -Dstash.home=/stash-home/atlassian/application-data/stash -Datlassian.org.osgi.framework.bootdelegation=META-INF.services,com.yourkit,com.singularity._,com.jprofiler,com.jprofiler._,org.apache.xerces,org.apache.xerces._,org.apache.xalan,org.apache.xalan._,sun._,com.sun.jndi,com.icl.saxon,com.icl.saxon._,javax.servlet,javax.servlet._,com.sun.xml.bind._ -Djava.endorsed.dirs=/opt/atlassian/stash/stash-current/endorsed -classpath /opt/atlassian/stash/stash-current/bin/bootstrap.jar:/opt/atlassian/stash/stash-current/bin/tomcat-juli.jar -Dcatalina.base=/opt/atlassian/stash/stash-current -Dcatalina.home=/opt/atlassian/stash/stash-current -Djava.io.tmpdir=/opt/atlassian/stash/stash-current/temp org.apache.catalina.startup.Bootstrap start

**Comment by george-vulov** [comment]
@pantzjantz Did you get YACC working with a later version by chance?
