### ISSUE TITLE
YACC working on some repos and not on others to block pushes

### ISSUE THREAD

**Issue by srizal** [mohamicorp/yet-another-commit-checker#114]
I have enabled YACC on few repositories. At this time all I am concerned about is blocking pushes that don't have a JIRA issue associated with it, so I have enabled that option in YACC. Strangely enough, this is working as intended on some repos (that is it blocks the push), while on others, it simply allows the push without a JIRA issue. I am totally confused as to what could be causing this. Can you provide some insight. We're still on Atlassian Stash v3.6.1, so using 1.8 version of the plugin.

Thank you in advance.

**Comment by sford** [comment]
> this is working as intended on some repos (that is it blocks the push), while on others, it simply allows the push without a JIRA issue.

Have you verified that all repos are configured to require JIRA issues? I can imagine this happening if some repos have the option enabled, but others do not.

**Comment by srizal** [comment]
Thanks for the response Sean. But unfortunately that is not the case. I am working only on a couple of repos for this testing phase. So I am making sure I am enabling them before my testing. I did it just now again after seeing your reply. Chose two repos, enabled hook  on both, one worked and blocked the push while the other one did not.

**Comment by sford** [comment]
If you have some time, could you [enable debug logging for YACC](https://github.com/sford/yet-another-commit-checker#enable-logging) in your Bitbucket Server instance and try pushing to those repositories? YACC will log what commits it sees and gives some information regarding the decisions it makes. That might help illuminate what is going on.

**Comment by srizal** [comment]
Manager is out on vacation until next week, will need his approval. Will enable the logging after talking to him if he has no objection. But I should note that this issue only seems to be on the version of Stash we're on (version noted in the original post). We have a newer version of BitBucket in our dev instance, and we have no issue there. When we didn't  hear back from you for a bit, we sort of decided that we will provide devs with a local commit-msg hook to block the commit without a JIRA id, and when we upgrade to latest Bitbucket in our Prod instance, we will start using YACC again.

________________________________

This message may contain confidential information and is intended for specific recipients unless explicitly noted otherwise. If you have reason to believe you are not an intended recipient of this message, please delete it and notify the sender. This message may not represent the opinion of Intercontinental Exchange, Inc. (ICE), its subsidiaries or affiliates, and does not constitute a contract or guarantee. Unencrypted electronic mail is not secure and the recipient of this message is expected to provide safeguards from viruses and pursue alternate means of communication where privacy or a binding message is desired.
