### ISSUE TITLE
Global Configuration

### ISSUE THREAD

**Issue by gabriellebautista** [mohamicorp/yet-another-commit-checker#119]
We would like to enable YACC on all our repositories (we have around 5000~ git repos) and we like to stay ENABLED so the project admins cannot DISABLE it. 

Is there anywhere we can hack this one? DB update? Server file config update?

**Comment by sford** [comment]
Hi @gabriellebautista ,

As you probably already discovered, YACC does support global configuration. However, as far as I know, admins can tweak settings however they want. So, I don't know how to prevent admins from tweaking settings you don't want them to.

For your requirements and scale, you might want to consider an audit approach. BitBucket Server keeps an [audit log](https://confluence.atlassian.com/bitbucketserver/audit-logging-in-bitbucket-server-776640417.html) of a [lot of events](https://confluence.atlassian.com/bitbucketserver/audit-events-in-bitbucket-server-776640423.html)... including enabling and disabling of plugins. The audit log can be check through the UI, the audit file on file system, or through a rest API. Using that, you can do whatever you want... you can check when admins change settings you don't want them too... or even use the BBS Rest API to revert setting changes.

**Comment by gabriellebautista** [comment]
Ok thanks for the info. Where does YACC store it's configuration if it's enabled/disabled per repository? We can hack that part.

**Comment by gabriellebautista** [comment]
Also, would there be any chance to customize the Error message so we can put out some informative stuff?

**Comment by sford** [comment]
> Where does YACC store it's configuration

It uses the BBS settings API to store and retrieve configuration. I don't know where it is stored... I assume database. Of your goal is to automatically configure YACC, BBS has [an hook settings API](https://developer.atlassian.com/static/rest/bitbucket-server/4.8.4/bitbucket-rest.html) to do this. 

> Also, would there be any chance to customize the Error message so we can put out some informative stuff?

Yes, YACC supports customized error messages for many of its checks as of 1.5.

**Comment by gabriellebautista** [comment]
Can YACC be configured to match the BBS "User Name" instead of the "Name"?
This will be my last question I promise :)
