### ISSUE TITLE
is there a way to know which specific commit message failed against the regex expression? 

### ISSUE THREAD

**Issue by AnkitaJain2** [mohamicorp/yet-another-commit-checker#121]
We're currently using YACC plugin to validate a developer's commit message against our regex expression. Our developers currently are making multiple commits with bad error messages and then they go through the rebase process to fix the messages individually. 

We print an error message every time there is a bad commit message. So for multiple bad commit messages, the error message gets printed multiple times. 

In this situation, is there a way to know which specific commit message failed against the regex expression?

**Comment by sford** [comment]
YACC errors contain the offending commit id, so, that could be used to lookup the commit and find the specific commit message.

**Comment by andys8** [comment]
Would be great to return the commit message, too.

**Comment by andys8** [comment]
Looked into the code:
https://github.com/sford/yet-another-commit-checker/blob/b873dd1c3dbc99c86f9fa56f22a4c9e8d6daccef/src/main/java/com/isroot/stash/plugin/YaccServiceImpl.java#L256-L257

could call and add `commit.getMessage()`.

**Comment by george-vulov** [comment]
Printing out the commit message could lead to clutter with large commit messages, obscuring the original error. It's relatively easy to run `git show` with the hash of the offending commit.
