### ISSUE TITLE
Yet Another Commit Checker on repositories over global YACC

### ISSUE THREAD

**Issue by glndgrgd** [mohamicorp/yet-another-commit-checker#122]
Is there a way for YACC global to override YACC on the repositories?
We need to set up commit messages restrictions on all repositories but if a repository already enabled their YACC, YACC on the repository will be enforced instead of the YACC setup on all repo.

**Comment by sford** [comment]
Nope. YACC global will only run for repositories that have YACC repo hook disabled. Once YACC is enabled on a repository, than global settings are no longer used.

If this is mission critical and you have a lot of repositories, you might consider using the [BBS REST API](https://developer.atlassian.com/static/rest/bitbucket-server/4.10.0/bitbucket-rest.html) to configure existing repos that are using YACC, or at least audit them. This would require some scripting work but could be worth it if you have strict auditing requirements.

**Comment by george-vulov** [comment]
Here's some relevant documentation on how to enable YACC via the REST API: [How to modify YACC settings programmatically](https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/1484652654/How+to+modify+YACC+settings+programmatically).
