### ISSUE TITLE
Push rejected for no JIRA number even though JIRA numbers are not required

### ISSUE THREAD

**Issue by amclin** [mohamicorp/yet-another-commit-checker#148]
We have YACC enabled, and the checkbox for Required Valid JIRA issue(s) unchecked. However, even with no other settings turned on, we still get error messages when pushing:

```
remote: Push rejected.        
remote: 
remote: refs/heads/skunkworks-plp: 1b6133916a639affc563fd853b3080185c48d6da: No JIRA Issue found in commit message.        
remote: 
To <anonymized server path>
 ! [remote rejected] skunkworks-plp -> skunkworks-plp (pre-receive hook declined)
error: failed to push some refs to '<anonymized server path>'
```

If we disable the YACC plugin on the repo, we still get the message. It's like it defaults on to all repos on our Bamboo server

**Comment by sford** [comment]
Hi @amclin,

> If we disable the YACC plugin on the repo, we still get the message. It's like it defaults on to all repos on our Bamboo server

Can you check YACC global settings to see if global settings are requiring JIRA issue id? Another thing to double check that YACC is being disabled on the correct repo that you are pushing to.

**Comment by amclin** [comment]
YACC is deffinitely disabled on the repo we're pushing to - I can replicate this in all our repos.

I don't have access to the global settings, but I'm trying to track that down, thanks

**Comment by judeogzewalla** [comment]
I just installed BitBucket 5.3.0 today and had pushes rejected by YACC (v 1.16), which was inactive in each repo.

I am unsure how to check global config because the UPM (in BB 5.3.0) doesn't have a "configure" button as shown in the Wiki link.

**Comment by sford** [comment]
@judeogzewalla Upgrading BBS may automatically disable plugins, which may require you to re-enable plugins. In YACC's case, the Configure button should be displayed again after enabling YACC in UPM.

As an example, here are the buttons after upgrading to BBS 5.3.1 and re-enabling YACC:
![image](https://user-images.githubusercontent.com/1066452/30253542-727e4a18-963c-11e7-863f-2772f4c53d8d.png)
