### ISSUE TITLE
Exclude Commits does not apply to matching committer name/email

### ISSUE THREAD

**Issue by Joshua-Barclay** [mohamicorp/yet-another-commit-checker#157]
Our use case for this plugin is to match committer name and email against the bitbucket user to ensure the identity of the commit. We want to exclude our CI users from this check.

My interpretation of the UI and documentation was that the 'exclude commits' configuration would apply to all checks, not just JIRA and commit message matching. Reviewing the code has confirmed this is not the case.

I'm not sure if this is an intentional design decision or not as the documentation is not specific as to how this should work.

**Comment by jojo221119** [comment]
We have the same issue. Would be great if the PR gets merged and into future versions.

**Comment by angvoz** [comment]
+1. Spent an hour trying to exclude a user or group from committer name/email check. The form suggests to enter "user names". Tried permutations such as user id, bitbucket frst name last name, names coming from commit, email id nothing works. Figured out that it works just for Jira issues only after cloning this repository and inspecting the code.

**Comment by george-vulov** [comment]
The fix for this is now released, see [version 1.25.0 on YACC Marketplace listing](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions).
