### ISSUE TITLE
Per Branch Configuration possible?

### ISSUE THREAD

**Issue by LpJohn** [mohamicorp/yet-another-commit-checker#163]
Is it possible to limit the rules to just one branch, such as master, while excluding the other branches in a repository?

**Comment by sford** [comment]
There is an 'Exclude Branch Regex' setting that might help. You could configure a regex to match all branches other than master.

**Comment by LpJohn** [comment]
OK, I'll check it out, thank you. Maybe that combined with branch level permissions will do the trick ...
