### ISSUE TITLE
YACC is disabled in BitBucket but it's refusing commits

### ISSUE THREAD

**Issue by tmescic** [mohamicorp/yet-another-commit-checker#169]
I have an empty repository on BitBucket server an a git repository locally. YACC is installed but it is **disabled** on my repository. Bitbucket version is 5.4, and YACC plugin version is 1.18. 
Local git repository contains commits by two different users. When I try to push to BitBucket I get to following error: 

`
$ git push
Password for 'https://user@pm.company.com': 
Counting objects: 402, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (177/177), done.
Writing objects: 100% (402/402), 143.54 KiB | 0 bytes/s, done.
Total 402 (delta 170), reused 385 (delta 163)
remote: Push rejected by YACC
remote: 
remote:   (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c) 
remote:    / ._. \      / ._. \      / ._. \      / ._. \      / ._. \ 
remote:  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__
remote: (_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)
remote:    || E ||      || R ||      || R ||      || O ||      || R ||
remote:  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '.
remote: (.-./`-'\.-.)(.-./`-`\.-.)(.-./`-`\.-.)(.-./`-'\.-.)(.-./`-`\.-.)
remote:  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-' 
remote: 
remote: 
remote: Push rejected.
remote: 
remote: refs/heads/master: b74da58fb0322728e9c176b9fa2cabd8d95de88a: expected committer email 'user1@company.com' but found 'user2@company.com'
remote: 
remote: refs/heads/master: e861b7ae10cb54e0e2262c72f92b382b738394cb: expected committer email 'user1@company.com' but found 'user2@company.com'
remote: 
`

![yacc_disabled](https://user-images.githubusercontent.com/4415205/31763442-90529d14-b4be-11e7-82ee-1586f33dcfce.png)

**Comment by sford** [comment]
@tmescic Can you check YACC global settings? If repository hook is disabled and global settings *are present*, then YACC will by default use global settings.

Check `Manage add-ons`:
![image](https://user-images.githubusercontent.com/1066452/31786645-0e7af836-b4be-11e7-9b8e-11ba2237b4eb.png)

**Comment by tmescic** [comment]
This was indeed the case (it was enabled in global settings). However, I don't find this very intuitive, I was expecting that I, as a repository administrator, can disable it. OR maybe an event better solution would be to have 3 options: Enabled, Disabled, Inherit from Global Settings.

**Comment by tmescic** [comment]
... or at least prevent me from disabling it if it's enabled in global settings.

**Comment by sgurusharan** [comment]
Hi @tmescic - I was lucky enough to find a workaround.

Click on Enable in the repository settings list and DO NOT check any of the rules and continue.

This makes the hook to read the rules from the repository rather than the global settings.

**Comment by sford** [comment]
> However, I don't find this very intuitive, I was expecting that I, as a repository administrator, can disable it. OR maybe an event better solution would be to have 3 options: Enabled, Disabled, Inherit from Global Settings.

I am a little late to this, but yes, I agree, it isn't that intuitive. Global settings are sort of hacked in there because BBS doesn't really have support for global settings.

BBS now has support for project settings, which is on my TODO list to add support for to YACC. Once that is in place, than it would be preferable to use project-level settings instead of global settings because they would be more intuitive to manage.
