### ISSUE TITLE
regex at repository level works but fails at global level

### ISSUE THREAD

**Issue by bb-tle** [mohamicorp/yet-another-commit-checker#170]
Hi Sean,
I tried "(^[A-Z][A-Z_0-9]+-[0-9]+):.*" which worked fine at the repo level, however if I tried it globally, the error: "commit message doesn't match regex..." resulted. I wonder if I'm missing something. Thank you.
--The-Binh

**Comment by sford** [comment]
Hi @bb-tle ,

Can you verify that repo and global settings are using the same regex? When you are testing the global regex, can you also verify that the YACC repo hook is *disabled* to make sure global settings are actually being used (global settings are only active for repo if YACC repo settings are disabled). The code for repo and global regex checks should be the same, so I am wondering if the configured settings are different.

**Comment by bb-tle** [comment]
They used identical regex (with other fields left defaults). The failures might have been caused by Bitbucket not being able to communicate with JIRA as mentioned below.

For repo level settings, if I used https as transport with username/password provided then the application link between Bitbucket and JIRA seemed to be used (after I had applied https://my-git.my-company.com/plugins/servlet/applinks/oauth/login-dance/authorize?applicationLinkID=xxxx-xxxx-xxxx-xxxx-xxxx from a web browser) and all worked fine. But if I used ssh as transport then the commits always failed like  Bitbucket could not talk to JIRA (even after I had authorized the communication between Bitbucket and JIRA via the application link, using https://my-git.my-company.com/plugins/servlet/applinks/oauth/login-dance/authorize?applicationLinkID=xxxx-xxxx-xxxx-xxxx-xxxx from a web browser).

**Comment by george-vulov** [comment]
@bb-tle Were you ever able to resolve this issue? 

Was the Bitbucket user the same in both cases (SSH and HTTPS)? If when using SSH you used an access token, the commit may have come in as a service user commit, rather than a regular commit. Check out the ["Exclude Service User Commits"](https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/1442119700/Yet+Another+Commit+Checker+YACC+for+Bitbucket#Exclude-Service-User-Commits) option.
