### ISSUE TITLE
Issue with implementing the exclude functionlity regext

### ISSUE THREAD

**Issue by amitcv86** [mohamicorp/yet-another-commit-checker#179]
Hi,
We are having pre-receive commit hook enabled which required username and email of the user on GIT client. And, it requires OPEN Jira Ticket # in message to commit any change.
My requirement is to skip these 2 checks in case the repo name ends with '_build or _deploy',
Can you please help me in implementing the same in plugin settings globally or per repo?

Thanks.

**Comment by philipooo** [comment]
Have you tried to place **.+(?:_build|_deploy)$** in **Exclude Branch Regex**? As I know you can not bypass checking of username/email.

**Comment by george-vulov** [comment]
[Version 1.25.0](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions) of YACC now applies exclusions (such as branch regex exclusion) prior to checking the username and email. I believe this likely addresses your issue.

You may also try using the ["Exclude Service User Commits"](https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/1442119700/Yet+Another+Commit+Checker+YACC+for+Bitbucket#Exclude-Service-User-Commits) option.
