### ISSUE TITLE
Able to edit global configuration as non admin user

### ISSUE THREAD

**Issue by benjiro** [mohamicorp/yet-another-commit-checker#181]
Noticed that if you navigate to the {BITBUCKET_URL}/plugins/servlet/yaccHook/config that any user is able to edit the configuration. When clicking save it does throw an error but the configuration will still save.

Solution:
- Use the UserManager to check if the user is admin or systemadmin

**Comment by sford** [comment]
Thanks @benjiro for reporting and the PR! Give me a moment to test and merge 👍

**Comment by wdawson4** [comment]
@sford  noticed this in an audit, do you need assistance to get this merged?

**Comment by george-vulov** [comment]
This is now fixed, in in [version 2.0.0](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions).
