### ISSUE TITLE
For a service users, on pushing the changes after changing the username in git config file. YACC allows the changes to be pushed.

### ISSUE THREAD

**Issue by RaviGH** [mohamicorp/yet-another-commit-checker#183]
For a service users, on pushing the changes after changing the username in git config file (git config user.name = userx).
 YACC allows the changes to be pushed, even after enabling the "Require Matching Comitter Name" in YACC.

**Comment by george-vulov** [comment]
Do you have the ["Exclude Service User Commits"](https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/1442119700/Yet+Another+Commit+Checker+YACC+for+Bitbucket#Exclude-Service-User-Commits) option enabled, by chance? This turns off all checks on commits made by service users.
