### ISSUE TITLE
Feature request : Activate commit checks on merge only

### ISSUE THREAD

**Issue by bric3** [mohamicorp/yet-another-commit-checker#184]
The scenario. In the repo of a private team, the workflow is to work with feature branches, no forks.

When we are working on those branches, it happens we commit unclean commits, e.g. 

- at the end of the day and pushing to the repo to avoid keeping something only on our laptops
- or to quick fix a few things

It is a work place, that need to be tidied up. But the commit checks can be delayed until the merge actions.

_Commit Policy Plugin for Bitbucket_ plugin integrates in the merge checks (the only issue is the hard dependency on jira). This plugin only integrates in the hook, that would be great to allow such usage.

**Comment by gsylvie** [comment]
Have you considered [Control Freak for Bitbucket Server](https://marketplace.atlassian.com/apps/1217635/control-freak-for-bitbucket-server?hosting=server&tab=overview) ?  I think it would meet your needs on this issue.

**Comment by laurentvaills** [comment]
> Have you considered [Control Freak for Bitbucket Server](https://marketplace.atlassian.com/apps/1217635/control-freak-for-bitbucket-server?hosting=server&tab=overview) ? I think it would meet your needs on this issue.

Can we configure Control Freak to prevent from merging if there are any commit matches some regexp ? (I'd like to prevent a user from merging if his PR contains some commits match this kind of regexp `^(WIP|fixup!|squash!).*`)

**Comment by laurentvaills** [comment]
As I can read from the doc, you almost have all the pieces to enable YACC as a merge-checker. 
I think an implementation of a `RepositoryMergeCheck` reusing most of the code you had in `YaccHook` could do the job.  
I don't think all the features of YACC fit for a `RepositoryMergeCheck` feature, but most of them would. I think only the "Branch Requirements" for a merge check plugin, also "Exclude Merge Commits" maybe.

**Comment by cerebro84** [comment]
To have it has a merge check instead of a repository hook would also be very useful in our workflow (git flow, pull request based).

**Comment by george-vulov** [comment]
The request of having YACC as a merge check is tracked on [YACC-264](https://mohamicorp.atlassian.net/browse/YACC-264). I hear you on the usefulness of this.

**Comment by george-vulov** [comment]
This is now released; as of [version 2.0.0](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions), YACC can be enabled either as a pre-receive hook or as a merge check.
