### ISSUE TITLE
YACC plugin for BitBucket Cloud

### ISSUE THREAD

**Issue by naga1023** [mohamicorp/yet-another-commit-checker#186]
Currently tested the YACC plugin for our test Bitbucket server. It suits our requirements and working fine. Now we are in plan to move towards BitBucket cloud, so would like to know if there is any plan to create YACC plugin for the bitbucket cloud. Please let me know.  

Thanks

**Comment by sford** [comment]
@naga1023 ,

BitBucket Cloud is a different product than BitBucket Server. YACC is specifically a BitBucket Server plugin. As far as I know, there isn't a way to install server plugins in their cloud product.
