### ISSUE TITLE
Question: How to validate the same Jira issue is both in the branch name and at the start of commit message

### ISSUE THREAD

**Issue by tlvu** [mohamicorp/yet-another-commit-checker#189]
Hi,

The use-case is to prevent use from typing the wrong Jira issue into the commit message.

We typically create the branch from Jira so there is no way to get the branch name wrong and the Jira issue will also be part of the branch name.

So if we can check that the same Jira issue that is in the branch name is also in the commit message, we are sure it is good.

This exclude branch master and develop of course.  This is for a bugfix/feature/hotfix/release or other custom type of branches.

Thanks

**Comment by george-vulov** [comment]
This request is tracked in #41

**Comment by george-vulov** [comment]
The option to have a matching Jira issue between the branch name and the commit messages is now released, in [version 2.0.0](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions)
