### ISSUE TITLE
Jira commit ID validation (Reject push if no valid jira id)

### ISSUE THREAD

**Issue by vramaprasad** [mohamicorp/yet-another-commit-checker#190]
Hi All, 

I am looking for a solution to validate Jira ID in commit message. if a valid Jira ID given in commit message user can push their changes to repo else reject their changes. 

I have implemented this for bitbucket using creating hook script and placed in bitbucket server for global users. Now i am looking for solution for github, as far as i know github does not allow custom script to run on their servers. so is there any way to validated all process using hooks or webhook or any third party opensource plugin. 

Thanks in advance. :)

**Comment by sford** [comment]
@agusmba  👍
