### ISSUE TITLE
Commit message regex fails for long commit messages (>2321 characters)

### ISSUE THREAD

**Issue by ghost** [mohamicorp/yet-another-commit-checker#191]
If YACC is configured to use "Commit Message Regex", it will fail for long commit messages.

**Steps to Reproduce**
1. Install YACC in Bitbucket
2. Enable the following setting YACC setting and no other settings: **Commit Message Regex** (.|\r|\n)*
3. Create a long commit message (example below)
4. git push
5. See error message:  ! [remote rejected] master -> master (pre-receive hook declined)
6. Remove one character
7. git push
8. See that the push is not rejected

**Example Commit Message**
> 12345678901234567890
> 123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901

**Comment by ata-sql** [comment]
We have same problem. Bitbucket 5.13.0, git 2.18.0.

**Comment by mergebase** [comment]
It's the "alternative" in the regex (that pipe: |) that's causing the problem:

https://stackoverflow.com/questions/7509905/java-lang-stackoverflowerror-while-using-a-regex-to-parse-big-strings

The Bitbucket Server logs should have something like this whenever you push:

```
[INFO] java.lang.StackOverflowError: null
[INFO] 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
[INFO] 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
[INFO] 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
[INFO] 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)

```

**Comment by GrayPockets** [comment]
The "alternative" in the regex (the pipe) is important for us, because we want to match anything after a Jira issue number and a space: [A-Z][A-Z_0-9]+-[0-9]+ (.|\r|\n)*
If we leave it at .*, we can't have any newlines in our commit messages: [A-Z][A-Z_0-9]+-[0-9]+ (.|\r|\n)*
Any suggestions on workarounds or better regex?

**Comment by GrayPockets** [comment]
Someone just introduced me to DOTALL notation, which apparently works fine in Bitbucket!
### Workaround
**Commit Message Regex** (?s).*

**Comment by george-vulov** [comment]
[Version 2.0.0](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions) detects this issue and offers an informative error rather than throwing an exception.
