### ISSUE TITLE
Branch Name Regex Error Message text

### ISSUE THREAD

**Issue by amenkov** [mohamicorp/yet-another-commit-checker#199]
I have Branch Name Regex in Branch Requirements and Branch Name Regex Error text defined which is supposed to be shown when branch name doesn`t match regex. However, when I`m trying to create branch with wrong name I see the default error message like "Branch creation canceled
Invalid branch name.  ...does not match regex " instead of error message that I defined.

**Comment by sford** [comment]
@amenkov How are you creating the branch? Pushing a new branch, or through the UI?

**Comment by amenkov** [comment]
@sford Through the UI. BTW When I push a new branch with git bash, I can see the error message that I defined.

**Comment by amenkov** [comment]
@sford So, is that normal behaviour that I can`t see defined error message when creating a branch through the UI?

**Comment by george-vulov** [comment]
@amenkov You're right, this is a bug in the code -- branch name creation through the UI doesn't display the custom error. The fix is tracked on [YACC-51](https://mohamicorp.atlassian.net/browse/YACC-51)

**Comment by george-vulov** [comment]
[YACC-51](https://mohamicorp.atlassian.net/browse/YACC-51) is now released, in [version 2.0.0](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions). Branch creation error messages in the UI should match exactly the ones produced when pushing a new branch.
