### ISSUE TITLE
Failing to compare commiter name with some Turkish characters

### ISSUE THREAD

**Issue by mehmet6parmak** [mohamicorp/yet-another-commit-checker#206]
Given error message is "Expected committer name is 'Çağatay' but found 'Çağatay'"

**Comment by george-vulov** [comment]
Hi @mehmet6parmak , we tried reproducing this and couldn't -- I successfully committed a change with "Çağatay" as the author name and the bitbucket user name. Maybe this was an issue with a mismatch in encodings, or a stray special character? 

Are you still running into this issue, and if so with what versions of Bitbucket / git / Yacc?

**Comment by mehmet6parmak** [comment]
@george-vulov it was an issue at my previous company and i don't currently have access to bitbucket. Thanks for your support 🙋
