### ISSUE TITLE
Trim trailing whitespace when saving commit message regex

### ISSUE THREAD

**Issue by tadhgpearson** [mohamicorp/yet-another-commit-checker#208]
When saving a commit message regex, trailing whitespace is preserved and applied as part of the regex. This creates a requirement that the commit message ends with trailing whitespace.

This type of error is easy for a user to make, but hard to catch... and it seems unlikely that admins would want to configure a regex to require the commit message to contain trailing white space. Perhaps it would be useful to trim trailing whitespace in the regex when saving the configuration, or when applying the regex. If not, it would definitely be useful to bring trailing whitespace to the attention of the user when saving.

**Comment by sford** [comment]
Makes sense 👍

**Comment by george-vulov** [comment]
This has been addressed in the latest version of YACC.
