### ISSUE TITLE
On some repos: YACC tells git client it rejected the push, when it actually accepted it

### ISSUE THREAD

**Issue by tbrixen** [mohamicorp/yet-another-commit-checker#214]
I seem to be experiencing the same as issue #114. I've included [logs from the server](https://github.com/sford/yet-another-commit-checker/files/2925860/atlassian-bitbucket.log) and additional information, which that issue was lacking.
As in issue #114 I also experience YACC working as intended on some repos, and on other repos it doesn't.

# Versions:
- Git (at developer machine) 2.20.1
- BitBucket Server 5.15.0
- YACC version 1.23
- SVN Mirror for Bitbucket Server 3.4.4

# Explanation

## Using global settings
I have the following global settings where (among other things) the following are enabled:
- Require Valid JIRA Issue(s)
- Ignore Unknown JIRA Project Keys

and at the repository the hook is _diabled_, which according to the YACC wiki, means that the global settings apply.

When I push a commit not containing a jira issue the client gets the (expected) error message:

```
$ git push
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 273 bytes | 91.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Push rejected by YACC
remote:
remote:                              __
remote:                    _ ,___,-'",-=-.
remote:        __,-- _ _,-'_)_  (""`'-._\ `.
remote:     _,'  __ |,' ,-' __)  ,-     /. |
remote:   ,'_,--'   |     -'  _)/         `\
remote: ,','      ,'       ,-'_,`           :
remote: ,'     ,-'       ,(,-(              :
remote:      ,'       ,-' ,    _            ;
remote:     /        ,-._/`---'            /
remote:    /        (____)(----. )       ,'
remote:   /         (      `.__,     /\ /,
remote:  :           ;-.___         /__\/|
remote:  |         ,'      `--.      -,\ |
remote:  :        /            \    .__/
remote:   \      (__            \    |_
remote:    \       ,`-, *       /   _|,\
remote:     \    ,'   `-.     ,'_,-'    \
remote:    (_\,-'    ,'\")--,'-'       __\
remote:     \       /  // ,'|      ,--'  `-.
remote:      `-.    `-/ \'  |   _,'         `.
remote:         `-._ /      `--'/             \
remote:            ,'           |              \
remote:           /             |               \
remote:        ,-'              |               /
remote:       /                 |             -'
remote:
remote: refs/heads/test-reject-commits-without-jira: 598de93d234cd60547cc174fe1acbae6314ecdd5: No JIRA Issue found in commit message.
remote:
remote:
remote: Fetching revisions from SVN repository:
remote:   up to date
remote: Sending commits to SVN repository:
remote:   598de93 => r170785 branches/test-reject-commits-without-jira
remote: Sync completed successfully
To ssh://gitserver.firm.com:7999/test-proj/test-repo.git
 ! [remote rejected]     test-reject-commits-without-jira -> test-reject-commits-without-jira (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@gitserver.firm.com:7999/test-proj/test-repo.git'
```

The ASCII art is a custom error message defined in the global settings. 
Issuing a `git status` tells me that I'm behind by 1 commit.

```
$ git status
On branch test-reject-commits-without-jira
Your branch is ahead of 'origin/test-reject-commits-without-jira' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```

But looking at the branch on Bitbucket, the commit was successfully pushed.
Sometimes it takes 2-3 minutes before the commit appears at the Bitbucket server.

## Using repository settings

If I change the state from _diabled_ to _enable_ and only enable 
- Require Valid JIRA Issue(s)
- Ignore Unknown JIRA Project Keys

I get the same behavior. 

## Explanation of the attached log

There are 3 event detailed in the log. 

- 08:12:02 Pushed a commit containing the commit message `thisisatestforlog`
- 08:12:57 The commit hadn't appeared at the Bitbucket server. Tried re-pushing it. The commit immediately appeared at the Bitbucket web gui.
- 08:13:33 Pushed a new commit containing the commit message `thisisanothertestforlog`

Some time after 08:13:33 (maybe 2-3 minutes) the commit appears at the Bitbucket web gui

### Git client printouts 

Printout at git client for the log at 08:12:02:
```
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 280 bytes | 93.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Push rejected by YACC
remote:
remote:                              __
remote:                    _ ,___,-'",-=-.
remote:        __,-- _ _,-'_)_  (""`'-._\ `.
remote:     _,'  __ |,' ,-' __)  ,-     /. |
remote:   ,'_,--'   |     -'  _)/         `\
remote: ,','      ,'       ,-'_,`           :
remote: ,'     ,-'       ,(,-(              :
remote:      ,'       ,-' ,    _            ;
remote:     /        ,-._/`---'            /
remote:    /        (____)(----. )       ,'
remote:   /         (      `.__,     /\ /,
remote:  :           ;-.___         /__\/|
remote:  |         ,'      `--.      -,\ |
remote:  :        /            \    .__/
remote:   \      (__            \    |_
remote:    \       ,`-, *       /   _|,\
remote:     \    ,'   `-.     ,'_,-'    \
remote:    (_\,-'    ,'\")--,'-'       __\
remote:     \       /  // ,'|      ,--'  `-.
remote:      `-.    `-/ \'  |   _,'         `.
remote:         `-._ /      `--'/             \
remote:            ,'           |              \
remote:           /             |               \
remote:        ,-'              |               /
remote:       /                 |             -'
remote:
remote: refs/heads/committerusername-test-reject-commits-without-jira: 3540329e81b0d5eb365b51f422a8c7795ca95bfe: No JIRA Issue found in commit message.
remote:
remote:
remote: Fetching revisions from SVN repository:
remote:   up to date
remote: Sending commits to SVN repository:
remote:   3540329 => r171161 branches/committerusername-test-reject-commits-without-jira
remote: Sync completed successfully
To ssh://gitserver.firm.com:7999/test-proj/test-repo.git
 ! [remote rejected]     committerusername-test-reject-commits-without-jira -> committerusername-test-reject-commits-without-jira (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@gitserver.firm.com:7999/test-proj/test-repo.git'
```

Printout at git client for the log at 08:12:57:
```
Total 0 (delta 0), reused 0 (delta 0)
remote: error: The following references updates will be rejected because they are out of date:
remote: error: refs/heads/committerusername-test-reject-commits-without-jira
remote:
remote: Fetching revisions from SVN repository:
remote: Updating refs:
remote:   598de93..3540329  branches/committerusername-test-reject-commits-without-jira -> committerusername-test-reject-commits-without-jira
remote: Sending commits to SVN repository:
To ssh://gitserver.firm.com:7999/test-proj/test-repo.git
 ! [remote rejected]     committerusername-test-reject-commits-without-jira -> committerusername-test-reject-commits-without-jira (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@gitserver.firm.com:7999/test-proj/test-repo.git'
```

Printout at git client for the log at 08:13:33:
```
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 292 bytes | 146.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Push rejected by YACC
remote:
remote:                              __
remote:                    _ ,___,-'",-=-.
remote:        __,-- _ _,-'_)_  (""`'-._\ `.
remote:     _,'  __ |,' ,-' __)  ,-     /. |
remote:   ,'_,--'   |     -'  _)/         `\
remote: ,','      ,'       ,-'_,`           :
remote: ,'     ,-'       ,(,-(              :
remote:      ,'       ,-' ,    _            ;
remote:     /        ,-._/`---'            /
remote:    /        (____)(----. )       ,'
remote:   /         (      `.__,     /\ /,
remote:  :           ;-.___         /__\/|
remote:  |         ,'      `--.      -,\ |
remote:  :        /            \    .__/
remote:   \      (__            \    |_
remote:    \       ,`-, *       /   _|,\
remote:     \    ,'   `-.     ,'_,-'    \
remote:    (_\,-'    ,'\")--,'-'       __\
remote:     \       /  // ,'|      ,--'  `-.
remote:      `-.    `-/ \'  |   _,'         `.
remote:         `-._ /      `--'/             \
remote:            ,'           |              \
remote:           /             |               \
remote:        ,-'              |               /
remote:       /                 |             -'
remote:
remote: refs/heads/committerusername-test-reject-commits-without-jira: d109f92669af3ee934283dfb18d28d27e85443a5: No JIRA Issue found in commit message.
remote:
remote:
remote: Fetching revisions from SVN repository:
remote:   up to date
remote: Sending commits to SVN repository:
remote:   d109f92 => r171162 branches/committerusername-test-reject-commits-without-jira
remote: Sync completed successfully
To ssh://gitserver.firm.com:7999/test-proj/test-repo.git
 ! [remote rejected]     committerusername-test-reject-commits-without-jira -> committerusername-test-reject-commits-without-jira (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@gitserver.firm.com:7999/test-proj/test-repo.git'
```

**Comment by kitaev** [comment]
Hello,

I'm SVN Mirror developer and was looking into this issue.

For Bitbucket Server 5.x and 6.x, YACC uses Bitbucket Server commit callback API to collect information on commits. Only when all commits have been traversed via this callback, it reports "REJECTED" result (in case commits doesn't match configured filters). 

This is, however, too late to prevent SVN Mirror pre-receive hook to transfer commits to SVN - it does so at hook "preUpdate" call.

So far I didn't find a way for SVN Mirror pre-recevie hook to run after YACC pre-receive hook and only in case YACC hook rejects the commit. The way YACC pre-receive hook works and Bitbucket Server hooks API is impleted it might be not possible.

One of the options would be for YACC add-on to resort back to analyzing commits in preUpdate using custom commit traversal code. Meanwhile I'll try to submit feature request to modify hooks subsytem behaviour to Bitbucket issues tracker.

**Comment by sford** [comment]
Hi @kitaev ,

Thanks for jumping on this and sharing this information.

> YACC add-on to resort back to analyzing commits in preUpdate using custom commit traversal code.

The BBS commit callback API was created to pretty much avoid custom commit traversal code. I think Atlassian ran into a lot of issues with plugins (including YACC) doing custom code dealing with commits. It is expensive calling out to git, for instance, and can cause problems in larger installs. 

What does SVN Mirror do in its `preUpdate`? Does it do custom commit traversal itself?

> Meanwhile I'll try to submit feature request to modify hooks subsytem behaviour to Bitbucket issues tracker.

Is feature request public? If so, can you include a link?

**Comment by tbrixen** [comment]
If there is anything I can do to help (logs, experiments etc) let me know.

**Comment by sford** [comment]
@tbrixen You could check in with maintainer of SVN Mirror.

> One of the options would be for YACC add-on to resort back to analyzing commits in preUpdate using custom commit traversal code. Meanwhile I'll try to submit feature request to modify hooks subsytem behaviour to Bitbucket issues tracker.

YACC is using the recommended BBS commit callback API to retrieve commit information and manage the acceptance or rejection of a push. Atlassian doesn't recommend custom commit traversal code, so it is highly unlikely I am going to rewrite YACC to do this :-) 

SVN Mirror maintainer said he was going to raise this issue with Atlassian in issue tracker, so you could follow up on that to see if Atlassian needs to update their plugin sub system to accommodate things like repository mirroring.

**Comment by george-vulov** [comment]
Closing -- the SVN Mirror plugin is doing irreversible updates in the context of the pre-receive git hook, when the commit may yet be rejected. This cannot be addressed on the YACC side.
