### ISSUE TITLE
Using variables within the branch name regex

### ISSUE THREAD

**Issue by paderka** [mohamicorp/yet-another-commit-checker#216]
Is it possible to check that only a specific user can only commit to the branch?

e.g. my username is _paderka_ (${BITBUCKET_USER_SLUG}) and I have branch _user/paderka/my-bugfix_. I want to be sure that only me is able to commit to that branch. Regex should be something like this `user/${BITBUCKET_USER_SLUG}/.{3,}`

**Comment by paderka** [comment]
@sford any suggestion, please?

**Comment by sford** [comment]
@paderka Not currently possible to add variables to the branch name regex.
