### ISSUE TITLE
YACC hook disabled automatically 

### ISSUE THREAD

**Issue by yashukumarkc** [mohamicorp/yet-another-commit-checker#221]
We have hundreds of repos where YACC plugin has enabled the hook with a condition "Require Valid JIRA Issue". In few(around 10) of the repos YACC hook vanished without an entry in the audit log trace and users are able to push without Jira ID in a commit message.

### Versions:
Git: 2.18.1
BitBucket Server: 5.14.2
YACC version 1.23

I can evidently see the entry for enabling hook and but not entry for disabling in Audit logs:

{"project":"DT","repository":"jan_patch","hook":"com.isroot.stash.plugin.yacc:yaccHook","settings":{"committerEmailRegex":"","commitMessageRegex":"","requireJiraIssue":true,"issueJqlMatcher":"","branchNameRegex":"","errorMessageHeader":"","errorMessage.COMMITTER_EMAIL":"","errorMessage.COMMITTER_EMAIL_REGEX":"","errorMessage.COMMITTER_NAME":"","errorMessage.COMMIT_REGEX":"","errorMessage.ISSUE_JQL":"","errorMessage.BRANCH_NAME":"","errorMessageFo

**Comment by sford** [comment]
Hi @yashukumarkc ,

YACC doesn't contain any code that enables or disables itself... it relies on BBS to turn it on or off (generally from some user admin action). Could there have been some BBS process that did this? Maybe check logs to see if you can determine when YACC was last active on affected repos? The fact that there is no audit log entry seems to suggest something on BBS might have been wonky at one point.
