### ISSUE TITLE
Blocks Commit Messages for Projects even when it is not enabled

### ISSUE THREAD

**Issue by gavarava** [mohamicorp/yet-another-commit-checker#227]
We did the following things recently:
- Installed the plugin from the marketplace
- configured a project X in Bitbucket to block if the commit message does not contain a jira id
It started blocking the same thing for other projects Y, Z etc even when it was not enabled for those.

**Comment by sford** [comment]
What BBS and YACC versions are you using? Do you have global settings configured?
