### ISSUE TITLE
Configuration where you can define for which branch this is only valid

### ISSUE THREAD

**Issue by petripanula** [mohamicorp/yet-another-commit-checker#229]
Now looks like I can only configure which branch(s) to exclude I think using reqex. But what about if I only what to configure this for master branch only - and not for any dev branch?

**Comment by george-vulov** [comment]
This behavior can be accomplished with the existing functionality using a little bit of regex magic. For example, if you want to do checks only on the branches `master` and `release`, but no other branch, configure the "Exclude Branch Regex" option like this:
`^(?!master$|release$).*`

All branch names other than `master` and `release` will be excluded, and thus the checks will only apply to those two branches.
