### ISSUE TITLE
Unable to enable and configure yet another commit checker plugin

### ISSUE THREAD

**Issue by rozal0906** [mohamicorp/yet-another-commit-checker#235]
Hi,
I am trying to enable this plugin for one of the project in bitbucket but unable to do so and getting error 'Unable to render configuration form for yet another commit checker'.
My plugin version is 1.24 and BB version is 6.5.1

**Comment by rozal0906** [comment]
Hi Team,
Can anyone please look into this issue ?

**Comment by sford** [comment]
@rozal0906 You might want to check BBS logs to see if there are any issues being logged. I have only seen errors like this during local development... not on a production BBS server. Does it only impact a single repo?

**Comment by rozal0906** [comment]
This issue is coming for all repos in BB.

**Comment by george-vulov** [comment]
Hi @rozal0906,

Please reproduce this issue again, so any error messages are available in the recent logs.

Then, create an Atlassian support zip, as [documented here](https://confluence.atlassian.com/support/create-a-support-zip-790796819.html) and attach it to the support ticket.

If you would like to submit this information privately, you can open a new support request [here](https://mohamicorp.atlassian.net/servicedesk/customer/portals) to attach the zip. In the the request description, mention this existing issue.

Thank you!

**Comment by george-vulov** [comment]
@rozal0906 I'm closing this issue for now. Please feel free to open a [new support request here](https://mohamicorp.atlassian.net/servicedesk/customer/portals), and attach the Atlassian support zip as outlined above.
