### ISSUE TITLE
Push rejected by YACC. Could not authenticate.

### ISSUE THREAD

**Issue by JWebDev** [mohamicorp/yet-another-commit-checker#239]
Hello, I have a problem with the YACC plugin. I can’t understand what the problem is.
There is a large project that consists of 50 modules. When I make a Jenkins build, several projects cannot be pushed because "YACC Could not authenticate".
Moreover, all the others, before and after error, pushed and everything is ok.

`[DEBUG] git< unpack ok
[DEBUG] git< ng refs/heads/develop pre-receive hook declined
[DEBUG] git< ng refs/heads/release/1.5.0 pre-receive hook declined
[DEBUG] git< 0000
[INFO] Push rejected by YACC

  (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c) 
   / ._. \      / ._. \      / ._. \      / ._. \      / ._. \ 
 __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__
(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)
   || E ||      || R ||      || R ||      || O ||      || R ||
 _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '.
(.-./`-'\.-.)(.-./`-`\.-.)(.-./`-`\.-.)(.-./`-'\.-.)(.-./`-`\.-.)
 `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-' 

Push rejected.

refs/heads/develop: caf1da0cd0081345345e314544b69959a4d64bcf: Bitbucket: Could not authenticate. Visit https://bitbucket-server/plugins/servlet/applinks/oauth/login-dance/authorize?applicationLinkID=556565fgf-6875-5656-3434-3434313824063 to link your Stash account to your JIRA account`

**YACC: 1.24
Atlassian Bitbucket Server v5.2.1**

**Comment by sford** [comment]
> When I make a Jenkins build, several projects cannot be pushed because "YACC Could not authenticate".

Try enabling "Exclude Service User Commits". If that doesn't fix this, then it implies that Jenkins is not using a service account, and instead using a regular user. Access keys (repo or project SSH keys) are typically used for CI... these service users can then be excluded.

**Comment by JWebDev** [comment]
Thanks for the answer.
But... This flag is enabled by default in all projects.

**Comment by george-vulov** [comment]
Hi @JWebDev,

YACC support and development has now transitioned to [Mohami](https://mohami.io).

Some followup questions to your issue:
* Sounds like pushing to some projects from Jenkins works, but fails for other repositories. Is this the case?
* Are the failing repositories consistent, or does the issue occur with different repositories every time? i.e. is there any nondeterminism?
* For the failing repositories, can you double-check that the "Exclude Service User Commits" YACC option is enabled? This option is not enabled by default
** Note that if YACC is enabled both on the project level and on the repository level, repository-level settings take precedence.

Thanks!

**Comment by george-vulov** [comment]
@JWebDev This is a pretty old issue, so I'm going to close it for now. Please feel free to open a support request in the [mohami support portal](https://mohamicorp.atlassian.net/servicedesk/customer/portals) if you're still experiencing this problem.
