### ISSUE TITLE
Empty commit message

### ISSUE THREAD

**Issue by K-4U** [mohamicorp/yet-another-commit-checker#241]
Not sure if this has already been asked, but i couldn't find it.
We have a developer that has finally learned not just to make 'WIP' commits, but to actually mention the jira ticket in the commit message.
This is great, but now he just commits the jira issue, without any message:
'JIRA-001'.
I'd love to be able to enforce to him to have a style of:
'JIRA-001 | Refactored to make code more readable'.

Is this possible with the current addon? Is this something you can add as a checkbox, to both require a jira issue _and_ a message after that?

**Comment by sford** [comment]
>  finally learned not just to make 'WIP' commits

👏 

> Is this possible with the current addon?

Yeah, that is possible using commit regex. Create a regex matching what you want (including min required length), and YACC will enforce it.
