### ISSUE TITLE
Configure Yet Another Commit Checker for Spesific Project

### ISSUE THREAD

**Issue by ArgelaTechnologies** [mohamicorp/yet-another-commit-checker#243]
Hello
We want to enable Yet Another Commit Checker for only 1 project on our Bitbucket server.
Because we are getting commit errors on other projects when enable the plugin
How can we do this?
Thanks

**Comment by sford** [comment]
You can use per-project or per-repo hook configuration to only enable YACC on a single project or repo.

**Comment by ArgelaTechnologies** [comment]
Thanks☺

Saygılar & Regards

Emrah GÜLTEKİN
IT Engineer

Argela Yazılım ve Bilişim Teknolojileri San. Ve Tic. A.Ş.

[argelalogo_big]
Istanbul | Ankara | Sunnyvale
Office: +90 212 707 50 00 | Direct : +90 212 707 51 52 Cell: +90 554 746 28 00 | Fax: +90 212 328 12 47
Reşitpaşa Mah. Katar Cad. No:4 İTÜ ARI Teknokent 3 İç Kapı No:502/601-604
34467 Maslak Sarıyer İstanbul
(İTÜ Ayazağa Kampüsü)
http://www.argela.com/
