### ISSUE TITLE
Failing the pr builds even after providing right JIRA ticket on Commit message.

### ISSUE THREAD

**Issue by sowmith1** [mohamicorp/yet-another-commit-checker#248]
Hello, 

We see pr build failures for particular users even after providing right JIRA Ticket on Commit message. We see this behavior particularly for couple of users but not for all.

Below is the error we see
===================================================================
Counting objects: 4, done.

Delta compression using up to 4 threads.

Compressing objects: 100% (2/2), done.

Writing objects: 100% (3/3), 271 bytes | 0 bytes/s, done.

Total 3 (delta 1), reused 1 (delta 0)

remote: Push rejected by YACC

remote:

remote:   (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)

remote:    / ._. \      / ._. \      / ._. \      / ._. \      / ._. \

remote:  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__

remote: (_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)

remote:    || E ||      || R ||      || R ||      || O ||      || R ||

remote:  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '.

remote: (.-./`-'\.-.)(.-./`-`\.-.)(.-./`-`\.-.)(.-./`-'\.-.)(.-./`-`\.-.)

remote:  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'

remote:

remote:

remote: Push rejected.

remote:

remote: refs/heads/feature/XXX-XXX-testing: 62c59a9437517519XXXXXXXXXX: No JIRA Issue found in commit message

remote:

remote:

To https://bitbucket.XXXXXXXXXXscm/ot/XXXXXX

! [remote rejected] feature/Test-463-testing -> feature/Test-463-testing (pre-receive hook declined)

error: failed to push some refs to 'https://bitbucket.xxxx.com/scm/ot/xxxx'
=====================================================================================

Please let me know if you need any further information to debug the issue.

Thanks
Sowmith.

**Comment by sford** [comment]
Hi @sowmith1 , I don't think there is enough in that output to tell what might be happening. That error should mean that the commit message didn't contain a JIRA issue. Do you have the commit message for `62c59a943751`?

**Comment by sford** [comment]
What is the commit message for `01f4b84e5`? I see the commit message for `d181d30a7`, and the JIRA issue was checked as expected. But, not sure where `01f4b84e5` came from. Does it's commit message not have a JIRA issue?

**Comment by LAkula1** [comment]
@sford seems in the above spoorthy missed two outputs may be.

Here is the complete output.
For the commit id: "c42f6cd0cc04cd6c4f060f1e43038264a5d1a265", we fed with valid ticket number "DOT-5067", and not able to push the same to bitbucket even we have ticket number in commit message.

--------------------
[root@salt01 jetblue-cms]# git branch
  develop
* feature/DOT-5067-new
[root@salt01 jetblue-cms]# git push origin feature/DOT-5067-new
Username for 'https://bitbucket.it.jetblue.com': shukla2
Password for 'https://shukla2@bitbucket.it.jetblue.com':
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 250 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
remote: Push rejected by YACC
remote:
remote:   (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)
remote:    / ._. \      / ._. \      / ._. \      / ._. \      / ._. \
remote:  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__
remote: (_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)
remote:    || E ||      || R ||      || R ||      || O ||      || R ||
remote:  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '.
remote: (.-./`-'\.-.)(.-./`-`\.-.)(.-./`-`\.-.)(.-./`-'\.-.)(.-./`-`\.-.)
remote:  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'
remote:
remote:
remote: Push rejected.
remote:
remote: refs/heads/feature/DOT-5067-new: **c42f6cd0cc04cd6c4f060f1e43038264a5d1a265**: No JIRA Issue found in commit message
remote:
remote:
To https://bitbucket.it.jetblue.com/scm/cms/jetblue-cms.git
 ! [remote rejected] feature/DOT-5067-new -> feature/DOT-5067-new (pre-receive hook declined)
error: failed to push some refs to 'https://bitbucket.it.jetblue.com/scm/cms/jetblue-cms.git'
[root@salt01 jetblue-cms]# git log -1
commit **c42f6cd0cc04cd6c4f060f1e43038264a5d1a265**
Author: admin <sneravetla@jetblue.com>
Date:   Wed Jun 24 07:34:05 2020 -0400

    **DOT-5067 new**
[root@salt01 jetblue-cms]#

**Comment by sford** [comment]
@LAkula1 What is the YACC settings for `jetblue-cms`?

**Comment by sneravetla** [comment]
@sford 
YACC is disabled at repo level for Jetblue-cms and all other repos. We had same issue when tried to commit to other repos as well.  
Here is the Global settting for YACC > 
@sford can we please have a working session so we can show you the issue and explain you better 
![image](https://user-images.githubusercontent.com/58852618/86000936-d1890780-ba2b-11ea-8912-1de02b27f90b.png)

![image](https://user-images.githubusercontent.com/58852618/86000980-e1a0e700-ba2b-11ea-878b-e66175b961d8.png)

**Comment by sford** [comment]
@sneravetla  @LAkula1 Enable debug logging for YACC and try testing again:
https://github.com/sford/yet-another-commit-checker/blob/master/scripts/enable_debug.sh

Replace the URL with your instance and an admin username. Once you do this, YACC will log exactly what is going on so you can track this down.

**Comment by iambhanuteja** [comment]
@sford Please find below logs. Let me know incase if you need more info on this.
2020-07-08 10:13:47,065 DEBUG [http-nio-7990-exec-995] shukla2 @1ONYMSTx613x2482741x0 183.83.144.36 "GET /scm/ot/cloud-provision.git/info/refs HTTP/1.1" c.a.bitbucket.scm.BaseCommand Executed /usr/bin/git http-backend

2020-07-08 10:13:54,884 INFO  [hook-callback:thread-1] shukla2 @1ONYMSTx613x2482749x0 183.83.144.36 "POST /scm/ot/cloud-provision.git/git-receive-pack HTTP/1.1" org.slf4j.Logger [OT/cloud-provision[317]] hook callback 'com.isroot.stash.plugin.yacc:yaccGlobalHook' vetoed the push request

2020-07-08 10:13:54,884 DEBUG [hook-callback:thread-1] shukla2 @1ONYMSTx613x2482749x0 183.83.144.36 "POST /scm/ot/cloud-provision.git/git-receive-pack HTTP/1.1" c.a.s.i.h.r.CachingRepositoryHookScmHelper [OT/cloud-provision[317]] Cleaning up repository-hook caches for request 94a18c12dc289d3b933d86748cdb286f1b650c0d

2020-07-08 10:13:54,928 DEBUG [http-nio-7990-exec-870] shukla2 @1ONYMSTx613x2482749x0 183.83.144.36 "POST /scm/ot/cloud-provision.git/git-receive-pack HTTP/1.1" c.a.bitbucket.scm.BaseCommand Executed /usr/bin/git http-backend

**Comment by iambhanuteja** [comment]
@sford Could you please reply on to this case asap.

**Comment by george-vulov** [comment]
Hi @iambhanuteja,

The log excerpt is missing some required information. Please 
1. reproduce the issue (so it's in the recent logs)
2. create an Atlassian support zip, as [documented here](https://confluence.atlassian.com/support/create-a-support-zip-790796819.html) and attach it to the support ticket
3. let us know the sha1 of the commit that was used to reproduce the issue

If you would like to submit this information privately, you can open a new support request [here](https://mohamicorp.atlassian.net/servicedesk/customer/portals) to attach the zip. In the the request description, mention this existing issue.

**Comment by iambhanuteja** [comment]
@george-vulov 

So here i am posting required info. Let me know incase if you need more info which i have missed...!!!

1) sha1 of commit id - 980244ad4ea08dcfe873100c0a4aaf586287de0b
2) Support ticket I need to attach zip file which consists of application logs but the file size is 200+ MB. Could you pls let me know where i need to upload. Here supporting size is just 10MB

**Comment by george-vulov** [comment]
To upload a large support zip, create a helpdesk ticket here: https://mohamicorp.atlassian.net/servicedesk/customer/portals

There will be an option to upload a file once the ticket is created. We can continue the conversation there.

**Comment by george-vulov** [comment]
This is now tracked in the Mohami support portal.
