### ISSUE TITLE
YACC 1.25 break "Apply Suggestion" functionality in BBS 7.40

### ISSUE THREAD

**Issue by fourofspades** [mohamicorp/yet-another-commit-checker#251]
Had some problem, where apply suggestion functionality wasn’t working.  I tried a lot of things to fix it, but in the end, reverting to YACC 1.24 was the only thing that fixed it for us.   

Even unticking the service accounts rule setting didn't fix things.

https://community.atlassian.com/t5/Bitbucket-questions/Are-code-suggestions-broken-in-Bitbucket-7-4/qaq-p/1453200#U1453885

**Comment by george-vulov** [comment]
Thanks for reporting this! Will try to reproduce

**Comment by aaremnev** [comment]
Hi.

In version 1.25 we have added checking of changes made from Bitbucket UI, see [YACC-110](https://mohamicorp.atlassian.net/browse/YACC-110) for description. And it looks like commit message in your case doesn't fit some of YACC rules and is being rejected properly. Unfortunately, new Bitbucket's **Apply suggestion** feature doesn't display details why it was rejected, while in other similar cases it is displayed properly (when you edit file from source viewer or try to merge pull request with invalid commit message). I have left [a feedback](https://community.atlassian.com/t5/Bitbucket-discussions/Bitbucket-7-4-0-quot-Apply-suggestion-quot-feature-feedback/td-p/1455798) for Atlassian team on this subject.

To understand why change is rejected you can [enable debug logging](https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/1475477597/Enabling+debug+logging) and look in Bitbucket logs for YaccErrorBuilder keyword - such log lines will explain the reason why change is rejected by YACC.

Also, I have created [YACC-267](https://mohamicorp.atlassian.net/browse/YACC-267) change request to make validation of such changes optional / configurable, it should be implemented soon.

Please, let me know if you have additional questions.

**Comment by fourofspades** [comment]
> To understand why change is rejected you can [enable debug logging](https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/1475477597/Enabling+debug+logging) and look in Bitbucket logs for YaccErrorBuilder keyword - such log lines will explain the reason why change is rejected by YACC.

Not seeing anything in the log, even with debug logging enabled.  They keyword isn't found. The best I found was this line:

**hook callback 'com.isroot.stash.plugin.yacc:yaccHook' vetoed the file-edit request**

**Comment by george-vulov** [comment]
@fourofspades Thanks for the update. We're working on a new exclusion option for commits made through the bitbucket UI. Should have it out next week.

**Comment by george-vulov** [comment]
@fourofspades The option to ignore Bitbucket UI commits was just released, in [YACC version 1.26](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=datacenter&tab=versions). Let us know if you run across anything else!
