### ISSUE TITLE
[Feature Request]: Need pre-commit hook or commitlint rule 

### ISSUE THREAD

**Issue by pgangwani** [mohamicorp/yet-another-commit-checker#252]
Hello Maintainer,
I would like to request pre-commit hooks which can be used in husky or [commitlint](https://commitlint.js.org/) rule so that can leverage to check git commit command. The reason is devs don't realize on commit but figure out in git push (error)

Please let me know if you need more info on this, can work/contribute with you.

Thanks,
Pawan

**Comment by george-vulov** [comment]
Unfortunately the way YACC is implemented is deeply embedded within the Bitbucket server API. It is not possible to provide it as a local pre-commit hook; that would have to be a separate project.

Thanks for your suggestion,

-- George
