### ISSUE TITLE
Bitbucket YACC plugin issue with JIRA integration

### ISSUE THREAD

**Issue by basilboonk** [mohamicorp/yet-another-commit-checker#254]
**Issue Detail**

We were using bitbucket YACC plugin and it was working fine till we changed the meathod of commit checker to just a JIRA ticket.

After that some users getting the below error (funny part is not all users getting the same) and not even getting the Commit error message updated in the YACC plugin.

```
Delta compression using up to 2 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 381 bytes | 381.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Repository hook com.isroot.stash.plugin.yacc:yaccHook failed
remote: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12
To https://bitbucket.com/scm/cc/repo.git
 ! [remote rejected] test_branch -> test_branch (pre-receive hook declined)
error: failed to push some refs to 'https://bitbucket.com/scm/cc/repo.git'
```

**Details on what we have checked and respected version:** 
Bitbucket version : v6.8.2
Bitbucket Yacc plugin version : 1.24
JIRA version : v8.5.7#805007
Application link connected with Oauth (since both having different user base)

We have tested the same in our test Bitbucket and JIRA instance (which is connected to the same respective user base) . the same user tried on that and on the first push the user got the URL for authetication to the remote.
when he accessed the URL and allowed the permission, after that the push with JIRA ticket worked perfectly.

Any idea on why is this happening to some users ?

**Comment by mdavoodi** [comment]
Hi basilboonk, support for YACC has moved to https://mohamicorp.atlassian.net/servicedesk/customer/portals. Can you please open a ticket there?

Mohammed
