### ISSUE TITLE
Feature Request: Option to require that JIRA issue in comment matches branch name

### ISSUE THREAD

**Issue by spoage** [mohamicorp/yet-another-commit-checker#41]
It'd be super handy if the plugin provided a way to match that the JIRA issue provided in the comment matches the name of the branch being pushed to. That way it would provide an easy way of enforcing that the feature branches that are created are provided in a way that JIRA is expecting.

**Comment by sford** [comment]
Hi @SPoage , I added branch name checking on push as part of #31 . It doesn't go as far as requiring that the JIRA issue matches the issue in the branch name; however, it does help ensure that feature branches are named in a way that JIRA expects. Just a FYI in case it helps.

**Comment by tkucorporate** [comment]
Hi Sean, I'd also be very happy if this feature could be implemented. 
I've run into the problem committing with the wrong issue number (e.g. TOOLS-1243) to the feature/bugfix branch (e.g. feature/TOOLS-1234) for several times now. A commit reject in case of a mismatch would be awesome..

Thanks in advance

Thomas

**Comment by pietervdheijden** [comment]
I would definitely use this feature!

**Comment by george-vulov** [comment]
The option to have a matching Jira issue between the branch name and the commit messages is now released, in [version 2.0.0](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions)
