### ISSUE TITLE
Feature request: Configurable per-branch

### ISSUE THREAD

**Issue by donmccasland** [mohamicorp/yet-another-commit-checker#88]
Is there any way to apply the rules only to some branches?  We have a development model where some branches require JIRAs, but other branches do not until they land them into the other branches.  We would love a way to configure which branches the rules apply to.

I also agree that this plugin rocks.  It is the swiss army knife for hooks!

**Comment by sford** [comment]
Thanks for the kind words :-) There isn't a way to currently only apply rules to certain branches. YACC does have a collection of 'exclude' configurations, so it probably wouldn't be too difficult to add a  'exclude  branch' setting, or something similar.

**Comment by adoorbijoy** [comment]
I completely agree the usefulness YACC hook and we are using it for all repo commits across all branches. Now we are in need of excluding certain branches for YACC check, but unfortunately it's not supported yet. I'm eagerly waiting for this feature on live.

**Comment by benjaminrupp** [comment]
I am also interested in the above mentioned feature.

**Comment by sford** [comment]
branch exclusion added in #133

**Comment by Macarse** [comment]
@sford when are you planning to do a release with this change?

**Comment by george-vulov** [comment]
This behavior can be accomplished with the existing functionality using a little bit of regex magic. For example, if you want to do checks only on the branches `master` and `release`, but no other branch, configure the "Exclude Branch Regex" option like this:
`^(?!master$|release$).*`

All branch names other than `master` and `release` will be excluded, and thus the checks will only apply to those two branches.
