### ISSUE TITLE
Service Account exclusion fails on branch name

### ISSUE THREAD

**Issue by ebucking** [mohamicorp/yet-another-commit-checker#90]
We need the exclusion to be complete, commit message, branch names, emails -- the whole magilla.

**Comment by sford** [comment]
So, just to be explicit, adding 'Exclude by Branch Name' and 'Exclude by Committer Email' would meet your requirements (considering exclude by commit message already exists)?

**Comment by ebucking** [comment]
Yes, both features would be welcome, b ut especially the branch name exclusion. And, while I have your attention, how about exclusions for specific service accounts? (Thanks for responding.)

Eugene Buckingham
CGI Federal - PSG - CM Team

CONFIDENTIALITY NOTICE: Proprietary/confidential information belonging to CGI Group Inc. and its affiliates maybe contained in this message. If you are not a recipient indicated or intended in thismessage (or responsible for delivery of this message to such person), or you think for any reason that this message may have been addressed to you in error, you may not use or copy or deliver this message to anyone else. In such case, you should destroy this message and are asked to notify the sender by reply email.
